-- In this file you can set up all the properties and settings for your game mode.

-- CUSTOM GAME SETUP
CUSTOM_GAME_SETUP_AUTO_LAUNCH_ENABLED = true
CUSTOM_GAME_SETUP_AUTO_LAUNCH_DELAY = 3.0
CUSTOM_GAME_SETUP_REMAINING_TIME = 0.0
CUSTOM_GAME_SETUP_TIMEOUT = -1.0
CUSTOM_GAME_END_DELAY = 0.0
CUSTOM_GAME_SETUP_TEAM_ASSIGNMENT_LOCK = false
CUSTOM_GAME_DIFFICULTY = 1

-- MINIMAP
MINIMAP_ICON_SIZE_CREEP = 1
MINIMAP_ICON_SIZE_HERO = 1
MINIMAP_ICON_SIZE_RUNE = 1

-- CUSTOM VICTORY MESSAGE
CUSTOM_VICTORY_MESSAGE = 'The Counter-Terrorists have won!'
CUSTOM_VICTORY_MESSAGE_DURATION = 10.0

-- GOLD
GOLD_PER_TICK = 0
GOLD_TICK_TIME = 0.0
GOLD_STARTING = 500

-- TIMES
TIME_HERO_SELECTION = 30.0
TIME_PRE_GAME = 30.0
TIME_POST_GAME = 60.0
TIME_RUNE_SPAWN = 0.0
TIME_TREE_REGROW = 60.0

-- MISC
ENABLE_SAME_HERO_SELECTION = true
ENABLE_FIRST_BLOOD = false
ENABLE_HERO_RESPAWN = false
HIDE_KILL_BANNERS = true
USE_BASE_GOLD_BOUNTY_ON_HEROES = false
CUSTOM_HERO_XP_VALUES = false
UNIVERSAL_SHOP_MODE = false



MAX_NUMBERS_OF_TEAMS = 10
USE_CUSTOM_TEAM_COLORS = true
USE_CUSTOM_TEAM_COLORS_FOR_PLAYERS = true

TEAM_COLORS = {}


USE_AUTOMATIC_PLAYERS_PER_TEAM = false
CUSTOM_TEAM_PLAYER_COUNT = {}
CUSTOM_TEAM_PLAYER_COUNT[DOTA_TEAM_GOODGUYS]	= 8
CUSTOM_TEAM_PLAYER_COUNT[DOTA_TEAM_BADGUYS]		= 0
CUSTOM_TEAM_PLAYER_COUNT[DOTA_TEAM_CUSTOM_1]	= 0
CUSTOM_TEAM_PLAYER_COUNT[DOTA_TEAM_CUSTOM_2]	= 0
CUSTOM_TEAM_PLAYER_COUNT[DOTA_TEAM_CUSTOM_3]	= 0
CUSTOM_TEAM_PLAYER_COUNT[DOTA_TEAM_CUSTOM_4]	= 0
CUSTOM_TEAM_PLAYER_COUNT[DOTA_TEAM_CUSTOM_5]	= 0
CUSTOM_TEAM_PLAYER_COUNT[DOTA_TEAM_CUSTOM_6]	= 0
CUSTOM_TEAM_PLAYER_COUNT[DOTA_TEAM_CUSTOM_7]	= 0
CUSTOM_TEAM_PLAYER_COUNT[DOTA_TEAM_CUSTOM_8]	= 0